// ── The Rulebook: a full-screen page with pinned section headers ──

import useLockBody from "./useLockBody.js";

const SECTIONS = [
  ["THE BIGS", ["Eight clubs, one league, forever. Every season is 154 games — home and away series against the same seven rivals — then the top four fight through a best-of-5 semifinal and a best-of-7 final for the PENNANT CUP.", "The games play themselves. You are the GM: train players, buy gear, set the batting order, and build a club that can take the Cup. Pause any time; 1× watches every pitch, 4× hustles. MAX — a whole game every second — is a champion's privilege: it unlocks with your first Pennant Cup."]],
  ["THE TREADMILL", ["Every winter your rivals reload — and the further ahead of the pack you are, the harder they chase. Your own players lose a step each offseason too (never below league average). Standing still is falling behind.", "While the app is closed the season waits for you. Only the merch store keeps working while you're away — flat out for the first hour, then a trickle, for as long as its tier allows (8h stand, 12h team store, 24h flagship). Media deals only pay while games are on."]],
  ["HOW EVERY PITCH RESOLVES", [
    "1. Strikeout roll — pitcher Stuff vs batter Contact (Eye helps a little).",
    "2. Walk roll — batter Eye vs pitcher Control.",
    "3. Ball in play: the engine rolls a spray angle (0° = dead center, ±45° = the foul lines; each batter has a hidden pull tendency that skews it), a launch type (grounder / liner / fly), and a distance driven by Power.",
    "4. Past ±45° is foul territory — usually just a do-over, sometimes caught for an out.",
    "5. Clear the fence at that angle and it's gone. The wall is shallow at the corners, deep in center.",
    "6. Otherwise the fielder in that zone rolls their Defense to make the play. Grounders die in the infield, flies get run down, liners are hardest to catch.",
    "7. Even a routine play can be BOOTED for an error — sure-handed fielders boot fewer. A ground ball with a man on first and less than two outs can become a DOUBLE PLAY — good infields turn more of them.",
    "8. With runners aboard, a low-Control pitcher will occasionally throw a WILD PITCH: everyone moves up a base.",
    "9. On a hit, depth plus batter Speed decides single, double, or triple. Runners advance station to station.",
  ]],
  ["YOUR ROSTER", ["Nine position players, one starter, one reliever. Everyone has individual attributes — tap a player in the Roster tab to train them with money. Your starter tires after facing enough batters (Stamina); the reliever takes over automatically.", "BA and K% shown are real season stats, accumulated from actual at-bats."]],
  ["MONEY AND FANS", ["Every game sells tickets: 30% of your fans show up when the club is cold, up to 60% when your last ten games are hot — and playoff games SELL OUT. The turnstiles pay all game long — each half-inning drops its slice of the gate into your vault, and the winner's bonus lands at the final out. Playoff wins, series wins, and the Pennant Cup pay extra.", "Every win grows the fan base — a flat crowd of new believers for the win and each homer, plus a slice of your existing fans bringing friends, so a winning empire compounds into the hundreds of thousands. Win 3+ straight and the bandwagon rolls: each consecutive win draws bigger crowds (up to double). Fans surge a full quarter for a Cup, a tenth for a playoff berth, and drift away if you miss.", "At 1,500 fans you can open the merch stand — passive income every second, boosted by star players — and grow it into a team store, then a flagship store: bigger sales, longer away selling. Media deals multiply everything the store makes: regional TV doubles it, national triples it, and a coast-to-coast deal pays four times over.", "The stadium itself can be built out in the Front Office — parking, seats, concessions, and lights, tier by tier all the way to a 60,000-seat cathedral of baseball. Each tier costs money and needs a big enough fan base: parking raises the share of fans who attend, seats raise the crowd cap, concessions multiply every game's payout, and lights speed up fan growth after wins."]],
  ["PLAYERS ARE PEOPLE", ["Ratings run 0-100: 65 is league average, the 80s are stars, and 99 is the edge of human ability. Every player has a hidden CEILING on each attribute — the second notch on his training bars. Scouts can't teach what isn't there: once a stat is PEAKED, only gear can push it higher. Winter aging never lowers a ceiling, so veterans can re-train what time takes.", "But talent alone isn't enough — the LEAGUE DEVELOPMENT CAP holds every ordinary player's training to 76, rising 2 points with every Pennant Cup you win. Only FRANCHISE PLAYERS train past it, all the way to their natural ceiling. You hold two franchise tags to start and earn one more per Cup. A tag is a commitment: it stays on the man until he's traded or released, and elite training gets steeply more expensive past 78 — a true superstar is built, not bought overnight.", "Every player also carries one TRAIT — a defined percentage shift on his ratings, shown right on his badge and baked into his bars. A Free Swinger really is +9% POWER and -9% CONTACT; a Gold Glove fields +9% better; a Workhorse pitches deeper. Because traits are percentages they scale with the player — an elite Free Swinger gives up more contact than a rookie one. Clutch hitters and Escape Artists are situational: their boost only fires with runners on base."]],
  ["THE CARDS", ["Every player in the league is a baseball card, and every card starts the same: COMMON, base set, plain cardboard. Nobody prints a chase card for a league-average filler guy. Tap a player, then VIEW CARD to hold his.", "Talent earns the right to reprint him. Cross 70 OVR and he's eligible for UNCOMMON (foil-stamped nameplate). Cross 80 — the star line — and it's RARE HOLO, a rainbow that moves when you tilt the phone. Cross 88 and he's a ONE-OF-ONE gold refractor, stamped 1/1, because only one exists. Remember the development cap holds ordinary men at 76: a RARE card can only ever come from a FRANCHISE PLAYER.", "Eligibility is free; the press is not. Printing costs $750, then $10,000, then $50,000, and you climb the ladder one step at a time. A printed card is never unprinted — winter can cost a man a step of talent, but the card he earned stays in your collection forever.", "Rarer cards sell more merchandise every second, and rivals charge more to pry a holo star out of your clubhouse. Chase the pennant; chase the card."]],
  ["THE PRO SHOP", ["A rotating shipment of one-of-a-kind gear: every series brings new stock and the old shipment leaves forever. Items boost their slot's attribute by a PERCENTAGE (+5% COMMON, +10% RARE, +15% LEGENDARY) and rarer pieces carry a ±4% side-effect on a second attribute. Boosts multiply the player's rating and cap at 99 — gear helps the great more than the mediocre, but nobody passes perfect.", "Rarity follows prestige: local dealers stock no legendaries — make the playoffs to attract them, win the Cup for the champion's catalog. Each winter the WINTER CATALOG arrives: rare and legendary stock only, timed for your playoff money (your first winter always dangles exactly one legendary). Gear stacks above a player's ceiling and never ages — but it travels with him if he's traded or released to the draft (draft rookies inherit it)."]],
  ["PAYDAY", ["Every player draws a seasonal salary that grows steeply with his effective rating — gear and training included. Position sets the scale: starting pitchers earn the most, shortstops and center fielders carry a premium, catchers come cheaper. Wages are paid out of every regular-season gate (the postseason is house money).", "Team payroll is measured against the league cap. Finish the year over it and the winter bills a LUXURY TAX: 100% of the overage the first year, and the rate climbs 50% for every consecutive year you stay over. Dip back under and the counter resets."]],
  ["TRADES & THE DRAFT", ["The TRADE DESK (Roster tab) swaps your player position-for-position with any rival. Pricing is straight value: upgrading costs a premium in cash, downgrading pays you back less than you'd hope. Gear moves with the players.", "Every winter is DRAFT DAY: a class of raw rookies with low stats and big ceilings — and the worse you finished, the better the prospects. Signing one releases your player at that position (the rookie inherits his gear). The season waits until you close the board."]],
  ["YOUR RIVALS", ["The same seven clubs share the league with you forever, each built around a trait — HR Sluggers, Defensive Wizards, Small Ball, Pitching Factory, Grinders — and each fields marquee stars of its own. Their batted balls run through the same physics engine as yours, their rosters persist, and they develop all season long, series by series, then retool hard every winter — no ceilings for them, just churn. The further ahead of the pack you get, the harder they chase."]],
];

export default function Rulebook({ onClose }) {
  useLockBody();
  return (
    <div className="page-screen" role="dialog" aria-label="Rulebook">
      <header className="page-screen__bar">
        <h2>The Rulebook</h2>
        <button onClick={onClose}>Close</button>
      </header>
      <div className="page-screen__body">
        {SECTIONS.map(([t, ps]) => (
          <div key={t}>
            <div className="page-screen__section">{t}</div>
            {ps.map((p, i) => <p key={i} style={{ fontSize: 12, lineHeight: 1.65, margin: "6px 2px" }}>{p}</p>)}
          </div>
        ))}
      </div>
    </div>
  );
}
